services:
  web:
    # command: python core/health_expenses/manage.py runserver 0.0.0.0:8000
    command: waitress-serve --listen=*:8000 health_expenses.wsgi:application
    build: .
    volumes:
      - .:/app
    ports: 
      - "8000:8000"

